Repository raksul/DoctrineSetTypeBundle, pull requests merged in 2023-07, with the labels that each got.

#4 Change the CI from Travis to GitHub Actions
  .github/workflows/continuous-integration.yml
  .travis.yml
  composer.json
Labels: size/L

#5 Support for PHP 8.0
  .github/workflows/continuous-integration.yml
  Tests/DBAL/Types/AbstractSetTypeTest.php
  Tests/Form/Guess/SetTypeGuesserTest.php
  composer.json
Labels: size/S

#6 drop support symfony2.8 and symfony4.x(which is not completely implemented)
  composer.json
Labels: size/XS
